// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwtAcKbr2YFvAjGs8yJowqxBJDXIb-tC0',
    appId: '1:1064395812800:web:0c3895374fe5798f83a225',
    messagingSenderId: '1064395812800',
    projectId: 'smart-home-b6da7',
    authDomain: 'smart-home-b6da7.firebaseapp.com',
    databaseURL: 'https://smart-home-b6da7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-b6da7.firebasestorage.app',
    measurementId: 'G-JG1W910Q4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh0tuk3ZzRXLbRSY14R5JdwXHdGqx_5B8',
    appId: '1:1064395812800:android:fb6d9555cf11441883a225',
    messagingSenderId: '1064395812800',
    projectId: 'smart-home-b6da7',
    databaseURL: 'https://smart-home-b6da7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-b6da7.firebasestorage.app',
  );
}
